name: Python Unit Tests
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      run: |
        make install_dev
        pytest tests/validation_tests.py --package astronomer-cosmos
