name: CI
on: [push]
jobs:
  ship-package-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # run only if 'astronomer-cosmos' was changed
    - name: astronomer-cosmos
      if: startsWith(github.ref, 'refs/tags/astronomer-cosmos-v')
      run: |
        make install_dev
        cd ${GITHUB_WORKSPACE}/astronomer-cosmos
        make build
        make ship
      env:
        TWINE_USER: "__token__"
        TWINE_PASS: ${{ secrets.PYPI_TOKEN }}
