name: Python Unit Tests

on:
  pull_request:
  push:
    branches: main

jobs:
  tests:
    if: github.head_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check PyPi Version
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install requests
          pytest tests/validation_tests.py
